export const data = [
    {
        id: 1,
        name: "Elemer Laverty",
        avatar: "https://i.pravatar.cc/150?img=11",
        email: "elemar@gmail.com",
        phone: "+92 300 1234567",
        about: "Frontend Developer 💻",
        lastSeen: "Today at 2:30 PM",
        lastMessage: "Haha that's funny 🔥",
        time: "12m",
        about: "Developer",
        unread: 2,
        online: true,
        active: false,
    },

    {
        id: 2,
        name: "Florencio Dorrance",
        avatar: "https://i.pravatar.cc/150?img=12",
        email: "florencio@gmail.com",
        phone: "+92 301 9876543",
        about: "Engineer",
        about: "UI/UX Designer 🎨",
        lastSeen: "Yesterday at 9:15 PM",
        lastMessage: "Woohoooo 😄",
        time: "24m",
        online: false,
        active: true,
    },

    {
        id: 3,
        name: "Lavern Laboy",
        avatar: "https://i.pravatar.cc/150?img=13",
        email: "lavern@gmail.com",
        about: "QA",
        phone: "+92 302 1239876",
        lastSeen: "Today at 10:00 AM",
        lastMessage: "Haha that's terrifying 😂",
        time: "10h",
        unread: 5,
        online: false,
        media: [],
        links: [],
        documents: [],
    },
    {
        id: 4,
        name: "Alfonzo Schuessler",
        avatar: "https://i.pravatar.cc/150?img=17",
        email: "alfonzo@gmail.com",
        phone: "+92 321 7778899",
        lastSeen: "5 minutes ago",
        lastMessage: "Perfect!",
        time: "1m",
        unread: 0,
        online: false,
        media: [],
        links: [],
        documents: [],
    }, {
        id: 5,
        name: "Princess",
        avatar: "https://i.pravatar.cc/150?img=20",
        email: "alfonzo@gmail.com",
        phone: "+92 321 7778899",
        lastSeen: "5 minutes ago",
        lastMessage: "Perfect!",
        time: "1m",
        unread: 0,
        online: false,
        media: [],
        links: [],
        documents: [],
    }, {
        id: 6,
        name: "Alfonzo Schuessler",
        avatar: "https://i.pravatar.cc/150?img=21",
        email: "alfonzo@gmail.com",
        phone: "+92 321 7778899",
        lastSeen: "5 minutes ago",
        lastMessage: "Perfect!",
        time: "1m",
        unread: 0,
        online: false,
        media: [],
        links: [],
        documents: [],
    }, {
        id: 7,
        name: "Alfonzo Schuessler",
        avatar: "https://i.pravatar.cc/150?img=19",
        email: "alfonzo@gmail.com",
        phone: "+92 321 7778899",
        lastSeen: "5 minutes ago",
        lastMessage: "Perfect!",
        time: "1m",
        unread: 0,
        online: false,
        media: [],
        links: [],
        documents: [],
    },
    {
        id: 8,
        name: "Alfonzo Schuessler",
        avatar: "https://i.pravatar.cc/150?img=24",
        email: "alfonzo@gmail.com",
        phone: "+92 321 7778899",
        lastSeen: "5 minutes ago",
        lastMessage: "Perfect!",
        time: "1m",
        unread: 0,
        online: false,
        media: [],
        links: [],
        documents: [],
    },

    {
        id: 9,
        name: "Alfonzo Schuessler",
        avatar: "https://i.pravatar.cc/150?img=26",
        email: "alfonzo@gmail.com",
        phone: "+92 321 7778899",
        lastSeen: "5 minutes ago",
        lastMessage: "Perfect!",
        time: "1m",
        unread: 0,
        online: false,
        media: [],
        links: [],
        documents: [],
    },
];