export const users = [
    {
        id: 1,
        name: "Ayesha Khan",
        username: "@ayesha.khan",
        avatar: "https://i.pravatar.cc/150?img=32",
        status: "Online",
        mutualFriends: 12,
    },
    {
        id: 2,
        name: "Hamza Ali",
        username: "@hamza.ali",
        avatar: "https://i.pravatar.cc/150?img=15",
        status: "Offline",
        mutualFriends: 8,
    },
    {
        id: 3,
        name: "Sana Malik",
        username: "@sana.malik",
        avatar: "https://i.pravatar.cc/150?img=47",
        status: "Online",
        mutualFriends: 21,
    },
    {
        id: 4,
        name: "Usman Tariq",
        username: "@usman.tariq",
        avatar: "https://i.pravatar.cc/150?img=12",
        status: "Away",
        mutualFriends: 5,
    },
    {
        id: 5,
        name: "Zain Abbas",
        username: "@zain.abbas",
        avatar: "https://i.pravatar.cc/150?img=14",
        status: "Online",
        mutualFriends: 18,
    },
    {
        id: 6,
        name: "Mariam Noor",
        username: "@mariam.noor",
        avatar: "https://i.pravatar.cc/150?img=48",
        status: "Offline",
        mutualFriends: 9,
    },
    {
        id: 7,
        name: "Bilal Ahmed",
        username: "@bilal.ahmed",
        avatar: "https://i.pravatar.cc/150?img=18",
        status: "Online",
        mutualFriends: 14,
    },
    {
        id: 8,
        name: "Hira Fatima",
        username: "@hira.fatima",
        avatar: "https://i.pravatar.cc/150?img=44",
        status: "Away",
        mutualFriends: 6,
    },
];